// <auto-generated />
using MVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Category", b =>
                {
                    b.Property<int>("fldslno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fldslno"));

                    b.Property<int>("fldDisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("fldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fldslno");

                    b.ToTable("tblCategory");

                    b.HasData(
                        new
                        {
                            fldslno = 1,
                            fldDisplayOrder = 1,
                            fldName = "Test"
                        },
                        new
                        {
                            fldslno = 2,
                            fldDisplayOrder = 2,
                            fldName = "Test1"
                        },
                        new
                        {
                            fldslno = 3,
                            fldDisplayOrder = 3,
                            fldName = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
